- docs/contrib/content.md
- docs/contrib/getting-started.md
- docs/contrib/topics.md
- docs/handbook/network-communications.md
- docs/handbook/systems-administration.md
- docs/misc/oi-docs.md
Minor work on NAS section of network communications doc.
Cleaned and polished up contributor TODO list.
Added clarifications about how to use Git.
> Further preparation for going public with the docs site

- docs/handbook/getting-started.md
- docs/misc/openindiana.md
There are a number of changes here. In the DVD writing section some information has been removed (e.g console output of various commands) as it was not required and made the section too long.
Even though Github does not fully support all markdown features, it may still help to look at the finished version of the file in my fork: https://github.com/makruger/oi-docs/blob/master/docs/handbook/getting-started.md
Alternately you can download the whole thing as a zip or clone and run `mkdocs serve`
> pre-production edits

- docs/books/about.md
- docs/books/develop.md
- docs/contrib/content.md
- docs/contrib/getting-started.md
- docs/contrib/roles.md
- docs/contrib/style.md
- docs/handbook/appendix.md
- docs/handbook/common-tasks.md
- docs/handbook/getting-started.md
- docs/handbook/network-communications.md
- docs/handbook/systems-administration.md
- docs/misc/oi-docs.md
- docs/misc/openindiana.md
* Moved and expanded IPS help section
* Cleaned up html comments
* Reorganized NAS section
* Added an IPS to APT matrix
* Other minor fixes
> More pre-production edits

- docs/handbook/common-tasks.md
- mkdocs.yml
*  Worked on basic unix commands
* Added use_directory_urls option to mkdocs.yaml
> some small changes

- docs/contrib/getting-started.md
- docs/handbook/common-tasks.md
- docs/handbook/getting-started.md
- link_validator.py
* Added information about new MKDocs IPS package
* Added a link to a GIT tutorial
* Added a doc team note about default terminals
* Updated base URL
* Updated OI as KVM guest information
> misc edits

- docs/dev/userland.md
None of the getting started documents mention that the userland-incorporation may place version constraints on existing packages, so you might not be able to install your updated version for testing.
One thing about my example that's different from the rest of the documentation (so far) is that my example shows both the command being run and the output, to illustrate the type of error message someone might get when userland-incorporation is blocking a package update.  I don't know if there's a better way to format that example.
> Add info on how to relax a version constraint

- docs/contrib/getting-started.md
- docs/handbook/common-tasks.md
- docs/handbook/systems-administration.md
- link_validator.py
- makepdf.sh
This commit is a fix to a problem reported by Adrian Lucrèce Céleste on the OpenIndiana/oi-docs on Thu, 03 Aug 2017 01:19:08 +0000 (UTC).
The script throws an exception because it cannot retrieve the character set from a url which is understandable, given that the url is a pdf!
Please take a look at the fix and provide comments etc as you see fit
> Fix for link_validator failing

- docs/contrib/getting-started.md
- docs/handbook/common-tasks.md
- docs/handbook/systems-administration.md
- makepdf.sh
I did some small corrections to the language. I think these are  ok.
Using emacs should be ok as it has been blended in with vim.
The only contentious issue is my script to generate the documentation in pdf.  html is not particularly useful for reading lots of material: pdf is better especially on a tablet. Now generating the pdf manually is tedious and error prone. Thus, I wrote a script (really only for myself). Thought this might be useful for others, so I added this to the root directory.
There are lots of potential _policy_ issues which I've not read up on yet (sorry!), so it might be located in the wrong place, the pdfs might have to be generated in their own directory, etc. Just complain and I'll fix.
Maybe, you'd like to retain the script, possibly not; but it would be interesting …
> Small doc corrections. Add using emacs with markdown. New script to generate pdf doc.

- docs/handbook/common-tasks.md
I've fixed the linting issues that were present in #79. @makruger and @xen0l I don't know if you two have the power to close #79, but at least you can merge this since it passes.
> Bootloader section

- docs/handbook/systems-administration.md
If you do merge, maybe you should consider squashing my history as I tend to commit frequently.  I don't think it is necessary to retain all the history.
Only just added a section on RBAC, but there is still lots to do here.
The idea is simple: start off with su, then progress to sudo, then culminate in RBAC.  I tried to be as succinct as possible, but I don't think I've entirely succeeded.
I think the best way to avoid reading a huge admin book, is to mirror the stuff in system-administration in the manual 'Common Tasks' and place the commands in tables with little or no text. I've started doing this.  Anyone agree or disagree?
> Add RBAC and make previous material more coherent

- README.md
Other people have now contributed to the project, so it's probably only fair to add them to the authors list ;)
> [README] add others who've contributed to the docs

- docs/contrib/getting-started.md
- docs/handbook/common-tasks.md
- docs/handbook/getting-started.md
- docs/handbook/systems-administration.md
Fixed a few typos I noticed while reading part of the handbook, and improved a couple sections.
Note that I wrapped the lines I changed, because I believe it makes diffs more readable in the long run. Not sure whether or not this breaks the "one sentence per line" rule in contrib/style.md (it may be good to add a note about that either way). I can unwrap if needed.
> A few fixes and improvements

- docs/handbook/systems-administration.md
...and couple of linguistic changes.
> `zones-proxy` has to be installed in non-global zone as well

- docs/handbook/getting-started.md
> status=progress is not on macOS dd

- docs/dev/distribution-constructor.md
- mkdocs.yml
Depends on https://github.com/OpenIndiana/slim_source/pull/56
> Add distribution constructor documentation

- docs/handbook/systems-administration.md
Moved here some information from https://wiki.openindiana.org/oi/Building+in+zones
> Add documentation about configuring zones with dedicated IP stack

- docs/dev/legacy-consolidations.md
- mkdocs.yml
We should preserve this if wiki is decommissioned...
> Add documentation on building legacy consolidations

- docs/dev/building-openindiana.md
- docs/dev/distribution-constructor.md
- docs/dev/existing-tasks.md
- docs/dev/graphics-stack.md
- docs/dev/userland.md
I am also not a native speaker but the German language shares some similarities to the English language. I have also tried to enhance the wording in some rare locations.
> Some grammar fixes and clarifications for the dev section

- docs/dev/userland.md
This fixes the formatting and indentation issue described in #173
> Fix for #173 formatting and indentation

- docs/community-hcl/components.md
- docs/community-hcl/systems.md
Update info on Dell UEFI BIOS version, add Logitech C930e,
Also document an issue with the Intel I210 card
The I219 seems to work fine for me but sometimes the I210 hangs on DHCP aquire lease
> Update info on Dell UEFI BIOS version, add Logitech C930e

- docs/community-hcl/components.md
- docs/community-hcl/systems.md
Previous commit messed up the columns in the HCL
> Fix layout of columns, previous commit wrong columns

- docs/handbook/community.md
- docs/handbook/community/vagrant.md
docs on ruby 3.0.3 with DTrace enabled
> Document vagrant 2.2.20 on ruby 3.0.3

- docs/handbook/community/vagrant.md
Update vagrant doc from virtualbox 6.1.22 to 6.1.30  
Add a note on /etc/vbox/networks.conf
> vagrant: virtualbox 6.1.30 and /etc/vbox/networks.conf

- docs/handbook/community/texlive.md
Add documention on 
pkg install tk-perl
This installs the required Perl Tk package for the TeX Live GUI (graphical user interface)
> texlive: add tk-perl package

- docs/handbook/community.md
- docs/handbook/community/quikstor.md
- docs/handbook/systems-administration.md
- mkdocs.yml
Content on Disk Mounting and a page covering RDX Quikstor media.
> Migrate some content on Storage from the Wiki

- docs/handbook/community/samqfs.md
> Fix typo in samqfs doc #224

- docs/community-hcl/components.md
- docs/community-hcl/systems.md
Add the Dell Precision 7720 and Fujitsu T1330
> Hcl (Hardware Compatiblity list) Update

- docs/handbook/community/inputmethod.md
Add some information on hte HAL keyboard entry and the lshal command to check XkbLayout
> Add information on XkbLayout in HAL

- docs/handbook/sunray.md
Some update for SunRay instation on current OI
> Sunray: update document and migrate Python script to Python3

- docs/handbook/sunray.md
> Sunray: small update document

- docs/handbook/network-communications.md
Please note that I am not a professional, and I still am quite new to Illumos operating systems, and almost everything as a whole, I'm just showing the steps I went through to get NFS working on my server with an explanation, I feel some documentation is always better than no documentation.
I created a Kerberos place holder, cause I don't know much about it, and I do not trust myself to show secure ways to configure it.
> NFS server documentation for network-communications.md

- docs/dev/userland.md
Hello,
I added some information regarding COMPONENT_REVISION to the documentation.  Let me know if I got anything incorrect, and thanks.
> Add information on COMPONENT_REVISION to section on Creating Makefile
