.travis.yml
docs/books/develop.md

Looks like something changed on DLC in regards to folder containing opensolaris docs.
Fixed broken URL's to compensate.
Strange...even after fixing urls, link validator is still complaining.

fixed broken urls

---

docs/handbook/appendix.md
docs/handbook/common-tasks.md
docs/handbook/getting-started.md
docs/handbook/network-communications.md
docs/handbook/systems-administration.md
docs/index.md

Shortened section titles (makes for a cleaner navigation menu).
Substituted the word "Hipster" for "OpenIndiana" in many different places.
Added a few SMF commands, etc.

cleaned up section titles, added 'Hipster Handbook' to home page, etc.

---

docs/dev/userland.md

The [Quick start for oi-userland](http://docs.openindiana.org/dev/userland/) document has a step that recommends running an invalid Makefile target, check-environment.  I believe the correct target is env-check.
This change updates the doc to use the env-check target.

update Makefile target env-check for userland.md

---

docs/handbook/getting-started.md

I had to specify a language (java worked) for some code blocks to make the formatting ok. Try removing it to see what I mean. Maybe there is a way to specify no formatting.

improve commandline examples

---

makepdf.sh

Although pandoc was installed, a typo caused this error always to
appear.
Silly error causing this script never to work!
Example:
makepdf.sh -f ./docs/handbook/systems-administration.md

Fix error reporting pandoc not installed from makepdf.sh

---

docs/dev/graphics-stack.md
mkdocs.yml

This PR contains most important parts from https://wiki.openindiana.org/display/oi/Graphic+stack besides https://wiki.openindiana.org/display/oi/Intel+KMS+driver 'Testing' section. I consider this section should be moved to HCL.

Add 'Graphics stack' page from wiki

---

docs/dev/userland.md

Update `dev/userland.md`
* ~~mention that the default transforms are applied to all components.~~
* mention that some of the targets in `make-rules/ips.mk` apply some transforms automatically.
* remove an extra : for the libtool files item
* use the correct directory and name for the file generated by the `sample-manifest` target.

mention default transforms

---

docs/release-notes/2019.10-release-notes.md

Link to https://docs.openindiana.org in the Other Activities section had a typo

Fix typo in the link to docs.openindiana.org 

---

.travis.yml

It seems that pyYAML does not support Python 3.4, which got out of support, anymore:
```
...
Collecting PyYAML>=3.10 (from mkdocs==1.0.4->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz (268kB)
PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8
The command "pip install -r requirements.txt" failed and exited with 1 during .
```
See https://travis-ci.org/OpenIndiana/oi-docs/builds/636001956?utm_source=github_status&utm_medium=notification.

Travis CI, bump to Python 3.5

---

docs/release-notes/latest-changes.md

Per https://github.com/OpenIndiana/oi-userland/pull/5295.
Travis CI fails: https://github.com/OpenIndiana/oi-docs/pull/149.

GNU TLS v2 was obsoleted

---

docs/handbook/getting-started.md

In the [Installing OpenIndiana section of the getting started handbook](http://docs.openindiana.org/handbook/getting-started/#installing-openindiana), there's a placeholder asking for someone to write about "How to configure the Linux GRUB2 bootloader to chainload an OpenIndiana partition". This PR hopefully covers that.
It also corrects a typo regarding configuring the illumos loader with `chain_disk="disk0:"`. The Doc currently includes `set chain_disk`, but 'set' is only used with the prompt, not in config files, the loader complains of a syntax error if 'set' in used in config.
As an aside the man pages for loader don't mention 'chain_disk', nor does /boot/loader.help ([although it seems that it does in FreeBSD](https://forums.freebsd.org/threads/adding-entries-for-others-oses-to-bootl …

Document using GRUB to chainload

---

docs/dev/graphics-stack.md
docs/dev/userland.md

Without `set-publisher --search-first` there tends to be conflict when installing local packages - higher ranker publisher openindiana.org tends to be chosen and the system doesn't install what was build locally.

set userland as primary publisher

---

docs/handbook/community/squeak.md

Document the change of name that is being implemented.
The squeak packages are moved from pkg:/runtime to pkg:/runtime/smalltalk/*
The smalltalk subdirectory of runtime will contain squeak, opensmalltalk cog-spur and opensmalltalk stack-spur.
And also of course planning pharo and sistavm and newspeak and others ...

Rename squeak packages

---

docs/community-hcl/components.md
docs/contrib/markdown.md
docs/dev/legacy-consolidations.md
docs/dev/userland.md
docs/handbook/appendix.md
docs/handbook/common-tasks.md
docs/handbook/community.md
docs/handbook/community/squeak.md
docs/handbook/community/texlive.md
docs/handbook/getting-started.md
docs/handbook/network-communications.md
docs/handbook/systems-administration.md
makepdf.sh
pandoc-config.yaml
pandoc-filter.lua

This implements the **proper** fix mentioned in #181. As described in the commit, not all pages of the docs have been fixed. All pages, other than docs/books, which are generated by makepdf.sh have been fixed.
The pages in docs/books need to be restructured/rewritten as they use lists inside a table which is not proper markdown and cannot be converted to PDF using Pandoc. These pages all need more content. All of this is better done together as a future commit.

Fix makepdf.sh and replace HTML formatting with markdown equivalent

---

makepdf.sh

Content is from mebenn's PR #184, but with bash regex used to check pandoc version numbers. This is because pandoc version go above a minor version of 9 and don't always have a patch, so the check of >230 did not work as v2.13 was seen as 213.

Rework PR #184 - Add support for epub and different pandoc versions

---

docs/contrib/content.md
docs/contrib/getting-started.md
docs/dev/userland.md
docs/index.md
docs/misc/oi-docs.md
docs/misc/openindiana.md

Libera Chat has just marked their [one month milestone](https://libera.chat/news/one-month-of-libera-chat). OI has had channels on Libera Chat for much of that time and the old freenode channels have seen little activity since.
All the documentation still refers to freenode. Now that Libera Chat is established, it is possibly time to bring the documentation up to date. More details on the oi-dev mailing list.
This PR also removes links to the logbot website as this is no longer logging and has been shutdown.

Replace Freenode details with Libera Chat

---

requirements.txt

GitHub Actions automatically selects a newer version of the "Markdown" package compared to Travis CI (which uses 3.2.2), the newer version has different and incompatible behaviour. This different behaviour causes a rendering problem in the docs.
This happens because the dependency versions required by MkDocs are given as ">=". Since MkDocs 1.0.4 was released there have been many updates to the dependencies and this has now got to the point where the latest version of a dependency may not be compatible anymore.
Pinning these dependencies of MkDocs to a known good version helps to mitigate this problem.
This fixes the problem I mentioned in #191.

Pin versions for pip package dependencies

---

.github/workflows/deploy.yaml

This implements the idea set out in #195 to allow builds (but not deploy) to occur on PRs. It also adds the ability to automatically build the PDFs and when deploying, adds these to the website.
When deploying, the PDFs are built first and then mkdocs build & deploy is run. When just building based on a PR, the PDF build and mkdocs build are done in parallel (as mkdocs doesn't need the PDFs in order to build).

Add a build only job for Pull Reqs, Add PDFs to the build

---

.github/workflows/deploy.yaml

It seems some builds failed because the apt cache was outdated in the GitHub Actions build image. Updating it every time will prevent this happening again.

Fix outdated apt cache in Actions

---

docs/contrib/getting-started.md
docs/contrib/git.md
docs/contrib/tools.md
docs/contrib/topics.md
docs/dev/graphics-stack.md
docs/handbook/common-tasks.md
docs/handbook/openindiana-download-mirrors.md
docs/misc/openindiana.md
docs/release-notes/2017.04-release-notes.md
docs/release-notes/2017.10-release-notes.md
docs/release-notes/2018.04-release-notes.md
docs/release-notes/2018.10-release-notes.md
docs/release-notes/2019.04-release-notes.md
docs/release-notes/2019.10-release-notes.md
docs/release-notes/2020.04-release-notes.md
docs/release-notes/2020.10-release-notes.md

- Replace some general topic dead links with similar working equivalents.
- Replace other broken links with update versions (same site different URL or content moved to another website)
- Replace remaining dead links with Wayback Machine versions
- Remove links to mirrors which are not working

Update and fix broken links

---

docs/handbook/community.md
docs/handbook/community/vagrant.md
docs/handbook/getting-started.md

Notes on installing Vagrant.
Also modify the notes on Oracle Database because there are Vagrantfiles from Oracle to install recent Oracle Databases (RAC, Grid, Oracle 18, 19, 21.3 etc.)

Add notes on building Ruby 3.0.2 and installing Vagrant

---

docs/handbook/network-communications.md
docs/handbook/systems-administration.md

Migrate some of the remaining content from the System Administration section (4) of the old Wiki.
There's still some content left to check/update.

Migrate System Administration Wiki content

---

docs/handbook/community.md
docs/handbook/community/oracledb.md
docs/handbook/sunray.md
mkdocs.yml

Community pages didn't have their own links from the navigation menu, this fixes that. It also moves the Oracle Database info onto its own page. There's also a few fixes to ensure a consistent style across pages.

Tidy up Community pages

---

docs/handbook/getting-started.md
docs/misc/openindiana.md

OSDisc.com is no longer operating. See #213. This removes the references/broken links to it.

Remove references to OSDisc.com which has shut down

---

docs/contrib/tools.md
docs/contrib/topics.md
docs/handbook/pdfdocs.md
mkdocs.yml

The PDF version of pages have been available for a while now. It's time there was a page linking to them.
Also includes some fixes for indentation level consistency (fixes PDFs contents page formatting).

Add a page linking to PDF versions of the Handbook

---

docs/contrib/roles.md
docs/contrib/tools.md
docs/misc/oi-docs.md

- It seemed like it might be useful to mention the old Wiki in the history section.
- Travis is no longer used.

Update the docs history section + Replace references to Travis with GitHub Actions

---

requirements.txt

Required to fix this build error:
```
ImportError: cannot import name 'soft_unicode' from 'markupsafe'
```
Which is caused changes in the latest version of markupsafe (2.1.1)

Manually specify Python pip markupsafe version

---

docs/handbook/systems-administration.md

Some changes for the NetWork Configuration part of system administration handbook.
Rephrase some sentences about NWAM.
For example NWAM was described as a new approach from OpenSolaris, and that may have been true in 2008, but nowadays it does not make sense to document NWAM as something new, or to refer to OpenSolaris.  So removed that.
Also documented new things about the sysding service and /etc/sysding.conf for changing from Automatic to Manual mode.

NWAM and networking: add info on sysding

---

docs/handbook/getting-started.md
docs/handbook/legacy-branch.md

Move all information about USB Flash drive setup for old versions of OI to a separate page. Also move information about upgrading legacy OI dev to hipster to this separate page.
This information might still be useful for a few people, so it is worth keeping. But it should not be on the main installation page, especially as this page is already long.
Also add command to enable graphical login when installing MATE manually when using the text installation (this doesn't happen automatically - at least not any more).

Relocate info for old/legacy versions to a seperate page

---

docs/handbook/getting-started.md
docs/index.md

There are still some references and links to the old Wiki which should have been updated previously. Some mentions of the Wiki remain, but only as notes in relation to migrating old content.

Remove a few references to the old Wiki

---

makepdf.sh

This PR fixes the following in makedocs (aka makepdf.sh):
- verbose help (makedocs -h -v) was not working
- minor typos
- document variable PROCESS_THESE_DIRECTORIES in verbose help

Fix no verbose help and typos

---

.github/workflows/deploy.yaml

Our gh-pages deployment workflow relies on the `mkdocs-deploy-gh-pages` action. Since a recent change to Cython, which is a dependency of the `PyYAML` pip dependency, the wheel build inside the container for this action for this fails. [See these logs for the error](https://github.com/OpenIndiana/oi-docs/actions/runs/5706696076/job/15462963353).
This problem is preventing any further deployment of these docs. The solution is to use the built wheel for this dependency from pypi, avoiding any wheel build failures. This requires the Python version to be set to 3.9 (GitHub default is now 3.10). The `mkdocs-deploy-gh-pages` action also runs inside its own container complicating maintenance and these fixes.
Instead of trying to fix that 3rd party action, this PR removes it and does the …

Fix gh-pages deployment

---

mkdocs.yml

The search function is normally included by default, but needs to be manually added if other plugins are specified.

Add search function

---

docs/handbook/community/squeak.md

incorrect runtime/stack-spur in documentation
correct value is runtime/smalltalk/stack-spur

squeak: fix FMRI in pkg change-facet command

---

docs/handbook/community/texlive.md

based on email report, tested texlive 2024
binaries are not working on openindiana, but the binaries from texlive 2023 seem to work, which can be installed with --repository option as was already documented;
this commit does not change a lot to the document, as the cross platform installer documentation remains valid for any unix platform, but I add a note that the cross platform installer incorrectly identifies openindiana as solaris;
depending on what texlive distribution is doing, document can be updated again in the future

TeX Live:  add note on TeX Live 2023

---

docs/handbook/community/texlive.md

option for the install-tl script to use custom binaries from the maintainers of Tex Live

TeX Live: add link to custom binaries document

---

mkdocs.yml
requirements.txt

Add MkDocs dark mode
